# Generated by Django 5.2.5 on 2025-09-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0002_subscription_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='permissons',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
