# Generated by Django 5.2.5 on 2025-09-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0004_alter_subscription_permissons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='permissons',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['basic', 'pro', 'advanced', 'basic_ai'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
